convert .\AdjustmentLayer_16x.png .\AdjustmentLayer_16x.ico.ico
convert .\BoostTest_16x.png .\BoostTest_16x.ico.ico
convert .\Brightness_16x.png .\Brightness_16x.ico.ico
convert .\CodeTest_16x.png .\CodeTest_16x.ico.ico
convert .\ColorDialog_16x.png .\ColorDialog_16x.ico.ico
convert .\Contrast_16x.png .\Contrast_16x.ico.ico
convert .\ConvertToCodeWebTest_16x.png .\ConvertToCodeWebTest_16x.ico.ico
convert .\CSTestProject_16x.png .\CSTestProject_16x.ico.ico
convert .\DynamicImage_16x.png .\DynamicImage_16x.ico.ico
convert .\EnableDiagnostics_16x.png .\EnableDiagnostics_16x.ico.ico
convert .\FSTestProject_16x.png .\FSTestProject_16x.ico.ico
convert .\HistogramVisualizer_16x.png .\HistogramVisualizer_16x.ico.ico
convert .\HorizontalScrollViewer_16x.png .\HorizontalScrollViewer_16x.ico.ico
convert .\RecommendedTest_16x.png .\RecommendedTest_16x.ico.ico
convert .\TestJob_16x.png .\TestJob_16x.ico.ico
convert .\TestPlan_16x.png .\TestPlan_16x.ico.ico
convert .\TestProject_16x.png .\TestProject_16x.ico.ico
convert .\TestSuiteStatic_16x.png .\TestSuiteStatic_16x.ico.ico
convert .\Test_16x.png .\Test_16x.ico.ico
convert .\VBTestProject_16x.png .\VBTestProject_16x.ico.ico
