using BitMiracle.LibTiff.Classic;
using NUnit.Framework;
using SciTIF.Tests.ImageValidation;
using System;
using System.Collections.Generic;
using System.Drawing.Drawing2D;
using System.Formats.Asn1;
using System.IO;
using System.Linq;

namespace SciTIF.Tests;

/// <summary>
/// Test dimensions and pixel values from sample data against that generated by ImageJ (source of truth)
/// </summary>
internal class ImageValidationTests
{
    [Test]
    public void Test_ImageDatabase_ContainsEverySampleImage()
    {
        ImageDatabase db = new(SampleData.DataInfoFile);
        Assert.That(db.Count, Is.Not.Zero);

        foreach (string tifPath in SampleData.TifFiles)
        {
            string title = Path.GetFileName(tifPath);
            Assert.That(db.Infos, Contains.Key(title));
        }
    }

    [Test]
    public void Test_SampleImage_Dimensions()
    {
        ImageDatabase db = new(SampleData.DataInfoFile);

        foreach (string tifPath in SampleData.TifFiles)
        {
            Console.WriteLine(Path.GetFileName(tifPath));
            ImageInfo known = db.Infos[Path.GetFileName(tifPath)];
            TifFile tif = new(tifPath);
            Assert.That(tif.Width, Is.EqualTo(known.Width));
            Assert.That(tif.Height, Is.EqualTo(known.Height));
            Assert.That(tif.Frames, Is.EqualTo(known.Frames));
            Assert.That(tif.Slices, Is.EqualTo(known.Slices));

            if (known.Channels == 1 && tif.Channels == 4)
            {
                // RGB source image with 1 channel
                // is now represented as a RGBA image with separate channels
                Assert.That(tif.Channels, Is.EqualTo(4));
            }
            else
            {
                Assert.That(tif.Channels, Is.EqualTo(known.Channels));
            }
        }
    }

    [Test]
    public void Test_ExportSlices_5DSourceImage()
    {
        string tifFilePath = Path.Combine(SampleData.DataFolder, "C3Z4F5.tif");
        TifFile tif = new(tifFilePath);
        Assert.That(tif.Frames, Is.EqualTo(5));
        Assert.That(tif.Slices, Is.EqualTo(4));
        Assert.That(tif.Channels, Is.EqualTo(3));

        string outputFolder = Path.Combine(Path.GetTempPath(), "test-image5d");
        if (!Directory.Exists(outputFolder))
            Directory.CreateDirectory(outputFolder);

        for (int frame = 0; frame < tif.Frames; frame++)
        {
            for (int slice = 0; slice < tif.Slices; slice++)
            {
                for (int channel = 0; channel < tif.Channels; channel++)
                {
                    Image img = tif.Data.GetImage(frame, slice, channel);
                    string saveAs = Path.Combine(outputFolder, $"test5D-F{frame}-S{slice}-C{channel}.png");
                    img.SavePng(saveAs);
                    Console.WriteLine(saveAs);
                }
            }
        }
    }

}
